language: java
sudo: false

jdk:
  - openjdk6 # wayback machine in production is actually hotspot 1.6.0
  - openjdk7
  - oraclejdk7
  - oraclejdk8

matrix:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk8
